site_name: audio-dataset-converter examples
site_url: https://waikato-llm.github.io/audio-dataset-converter-examples/
repo_url: https://github.com/waikato-llm/audio-dataset-converter-examples
edit_uri: edit/master/docs/
site_description: Examples for using the audio-dataset-converter libraries
theme:
    name: material
markdown_extensions:
    - toc:
          baselevel: 2
          permalink: "#"
    - attr_list
plugins:
    - search
nav:
    - Home: index.md
    - Core library:
        - Audio classification: audio_classification.md
        - Speech: speech.md
        - Filter usage: filters.md
        - Placeholders: placeholders.md
        - Execution control: execution_control.md
        - External functions: pyfunc.md
        - Multiple I/O: multi.md
        - Email: email.md
        - File handling: file_handling.md
        - Temporary storage: storage.md
        - Docker usage: docker.md
    - Additional libraries:
        - Faster whisper: faster_whisper.md
        - Redis: redis.md
        - Visualization: visualization.md
